<Project Sdk="Microsoft.NET.Sdk" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

	<!-- 核心项目设置 -->
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<LangVersion>Latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<DebugType>none</DebugType>

		<!-- 指定输出的 DLL 名称  修改DLL文件的名称                 -->
		<AssemblyName>WeatherDisplayMod</AssemblyName>

		<!-- 输出路径 -->
		<OutputPath>bin\$(Configuration)\</OutputPath>
	</PropertyGroup>

	<!-- 游戏路径配置 -->
	<PropertyGroup>
		<TheLongDarkPath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark</TheLongDarkPath>
	</PropertyGroup>

	<!-- NuGet 包引用 -->
	<ItemGroup>
		<PackageReference Include="STBlade.Modding.TLD.Il2CppAssemblies.Windows" Version="2.51.0" />
		<PackageReference Include="STBlade.Modding.TLD.ModSettings" Version="1.9.0" />
	</ItemGroup>

	<!-- 全局 using 声明 -->
	<ItemGroup>
		<Using Include="System.Reflection" />
		<Using Include="System.Diagnostics.CodeAnalysis" />
		<Using Include="Il2Cpp" />
		<Using Include="HarmonyLib" />
		<Using Include="MelonLoader" />
		<Using Include="UnityEngine" />
		<Using Include="ModSettings" />
	</ItemGroup>

	<!-- 构建后自动复制到游戏 Mods 文件夹 -->
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(TheLongDarkPath)\Mods" />
		<Message Text="testMod.dll copied to game Mods folder" Importance="high" />
	</Target>

</Project>
